modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/CSneko/toNeko/issues"
license = "GPL-v3"

[[mods]]
modId = "toneko"
version = "${version}"
displayName = "toNeko"
displayURL="https://github.com/CSneko/toNeko"
authors = '''CrystalNeko
Contributors:MrHua269/Lora4967,pil0lo,QWERTY770,yichifauzi,HappyRespawnanchor,homewool,ΗγΤζΡβΒι
'''
description = '''
可爱即是正义!
'''
logoFile = "assets/toneko/icon.png"

[[dependencies.toneko]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.toneko]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.21.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.toneko]]
modId = "fabric_api"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

# [[dependencies.toneko]]
# modId = "luckperms"
# type = "optional"
# versionRange = "*"
# ordering = "NONE"
# side = "BOTH"

[[dependencies.toneko]]
modId = "geckolib"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.toneko]]
modId = "optifine"
type = "incompatible"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "toneko.mixins.json"
